language: csharp
solution: MonoApp.sln
notifications:
  email: false
install:
  - nuget restore MonoApp.sln
  - nuget install NUnit.Runners -Version 3.4.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release MonoApp.sln
  - mono ./testrunner/NUnit.Runners.3.4.1/tools/nunit-console.exe ./MonoApp.Test/bin/Release/MonoApp.Test.dll
